export const hero = [
  {
    id: 1,
    img: "/hero/Adagio.png",
    name: "Adagio",
    role: "Protector",
    description: "Team healer and damage enchancer with a large area stun",
    AttackType: "Ranged",
    offense: 50,
    defense: 20,
    teamUtility: 60,
    mobility: 5,
    difficulty: "Medium",
  },
  {
    id: 2,
    img: "/hero/alpha.png",
    name: "Alpha",
    role: "Warrior",
    description: "Killing machine who an resurrect herself",
    AttackType: "Melee",
    offense: 80,
    defense: 55,
    teamUtility: 10,
    mobility: 55,
    difficulty: "Hard",
  },
  {
    id: 3,
    img: "/hero/amael.png",
    name: "Amael",
    role: "Warrior",
    description:
      "A grizzled mercenary who spends his spare time fighting in the arena for fun",
    AttackType: "Melee",
    offense: 85,
    defense: 55,
    teamUtility: 47,
    mobility: 47,
    difficulty: "Hard",
  },
  {
    id: 4,
    img: "/hero/anka.png",
    name: "Anka",
    role: "Assassin",
    description: "Elusive assassin with trmendous burst potential",
    AttackType: "Melee",
    offense: 100,
    defense: 20,
    teamUtility: 10,
    mobility: 65,
    difficulty: "Hard",
  },
  {
    id: 5,
    img: "/hero/ardan.png",
    name: "Ardan",
    role: "Protector",
    description:
      " Protect allies with barriers and traps enermies inside a large cage",
    AttackType: "Melee",
    offense: 35,
    defense: 85,
    teamUtility: 70,
    mobility: 78,
    difficulty: "Easy",
  },
  {
    id: 6,
    img: "/hero/baptiste.png",
    name: "Baptiste",
    role: "Mage",
    description: "Mid-range mage who inflicts fear on foes",
    AttackType: "Melee",
    offense: 74,
    defense: 48,
    teamUtility: 90,
    mobility: 13,
    difficulty: "Medium",
  },

  {
    id: 7,
    img: "/hero/baron.png",
    name: "Baron",
    role: "Sniper",
    description: "Rocket soldier who can make anywhere on the map",
    AttackType: "Ranged",
    offense: 96,
    defense: 30,
    teamUtility: 20,
    mobility: 50,
    difficulty: "Medium",
  },
  {
    id: 8,
    img: "/hero/blackfeather.png",
    name: "Blackfeahter",
    role: "Assassin",
    description:
      "Evasive fighter who excels at chasing and cleaning up fragile enemies",
    AttackType: "Melee",
    offense: 75,
    defense: 66,
    teamUtility: 40,
    mobility: 88,
    difficulty: "Hard",
  },
  {
    id: 9,
    img: "/hero/caine.png",
    name: "Caine",
    role: "Sniper",
    description: "Hitman who wields his revolver with deadly accuracy",
    AttackType: "Ranged",
    offense: 93,
    defense: 20,
    teamUtility: 30,
    mobility: 40,
    difficulty: "Hard",
  },
  {
    id: 10,
    img: "/hero/catherine.png",
    name: "Catherine",
    role: "Protector",
    description: "Disruptive tank with lots of stuns and a powerful silence",
    AttackType: "Melee",
    offense: 20,
    defense: 80,
    teamUtility: 80,
    mobility: 20,
    difficulty: "Easy",
  },
  {
    id: 11,
    img: "/hero/celeste.png",
    name: "Celeste",
    role: "Mage",
    description: "Back-line mage heavy area damgage and a stun",
    AttackType: "Ranged",
    offense: 90,
    defense: 5,
    teamUtility: 34,
    mobility: 5,
    difficulty: "Medium",
  },
  {
    id: 12,
    img: "/hero/churnwalker.png",
    name: "Churnwalker",
    role: "Protector",
    description:
      "A disruptor who throws muliple skillshot hooks, chaining victims to him",
    AttackType: "Melee",
    offense: 70,
    defense: 70,
    teamUtility: 87,
    mobility: 25,
    difficulty: "Medium",
  },
  {
    id: 13,
    img: "/hero/flicker.png",
    name: "Flicker",
    role: "Proctector",
    description: "Trickster who can make the entire team invisible",
    AttackType: "Melee",
    offense: 48,
    defense: 20,
    teamUtility: 98,
    mobility: 35,
    difficulty: "Hard",
  },
  {
    id: 14,
    img: "/hero/fortress.png",
    name: "Fortress",
    role: "Protector",
    description: "Aggressive pack leader who swarms the enemy with great speed",
    AttackType: "Melee",
    offense: 53,
    defense: 45,
    teamUtility: 57,
    mobility: 57,
    difficulty: "Easy",
  },
  {
    id: 15,
    img: "/hero/glaive.png",
    name: "Glaive",
    role: "Warrior",
    description: "Brutal axe warrior who can knock enemies out of position",
    AttackType: "Melee",
    offense: 80,
    defense: 80,
    teamUtility: 75,
    mobility: 60,
    difficulty: "Easy",
  },
  {
    id: 16,
    img: "/hero/grace.png",
    name: "Grace",
    role: "Protector",
    description: "A powerful paladin with a massive heal",
    AttackType: "Melee",
    offense: 34,
    defense: 80,
    teamUtility: 90,
    mobility: 38,
    difficulty: "Easy",
  },
  {
    id: 17,
    img: "/hero/grumpjaw.png",
    name: "Grumpjaw",
    role: "Warrior",
    description: "A hungry beast who can swallow a hero whole",
    AttackType: "Melee",
    offense: 90,
    defense: 90,
    teamUtility: 38,
    mobility: 65,
    difficulty: "Easy",
  },
  {
    id: 18,
    img: "/hero/gwen.png",
    name: "Gwen",
    role: "Sniper",
    description:
      "Gunslinger with powerful burst damage and ability to shake off disables",
    AttackType: "Ranged",
    offense: 70,
    defense: 27,
    teamUtility: 70,
    mobility: 70,
    difficulty: "Easy",
  },
  {
    id: 19,
    img: "/hero/idris.png",
    name: "Idris",
    role: "Assassin",
    description: "Nimble assassin who unlocks melee or ranged fighting styles",
    AttackType: "Melee",
    offense: 97,
    defense: 20,
    teamUtility: 2,
    mobility: 100,
    difficulty: "Hard",
  },
  {
    id: 20,
    img: "/hero/inara.png",
    name: "Inara",
    role: "Warrior",
    description: "Dual bladed forest sipirit who thrives in the jugnle",
    AttackType: "Melee",
    offense: 83,
    defense: 14,
    teamUtility: 19,
    mobility: 96,
    difficulty: "Medium",
  },
  {
    id: 21,
    img: "/hero/ishtar.png",
    name: "Ishtar",
    role: "Mage",
    description: "Demonic queen who manipulates Living Blades",
    AttackType: "Ranged",
    offense: 97,
    defense: 553,
    teamUtility: 20,
    mobility: 35,
    difficulty: "Easy",
  },
  {
    id: 22,
    img: "/hero/joule.png",
    name: "Joule",
    role: "Warrior",
    description: "Heavily armored mech rider with a powerful energy beam",
    AttackType: "Melee",
    offense: 75,
    defense: 75,
    teamUtility: 45,
    mobility: 45,
    difficulty: "Medium",
  },
  {
    id: 23,
    img: "/hero/karas.png",
    name: "Karas",
    role: "Mage",
    description: "A mysterious teenager trained in the art of wind magic",
    AttackType: "Ranged",
    offense: 97,
    defense: 40,
    teamUtility: 10,
    mobility: 68,
    difficulty: "Medium",
  },
  {
    id: 24,
    img: "/hero/kensei.png",
    name: "Kensei",
    role: "Warrior",
    description:
      "Swift swordmaster who can easily maneuever through the battle field",
    AttackType: "Melee",
    offense: 90,
    defense: 20,
    teamUtility: 54,
    mobility: 100,
    difficulty: "Medium",
  },
  {
    id: 25,
    img: "/hero/kestrel.png",
    name: "Kestrel",
    role: "Sniper",
    description: "Stealthy archer with devastating skillshots & traps",
    AttackType: "Ranged",
    offense: 90,
    defense: 8,
    teamUtility: 20,
    mobility: 35,
    difficulty: "Hard",
  },
  {
    id: 26,
    img: "/hero/kinetic.png",
    name: "Kinetic",
    role: "Sniper",
    description: "Nimble duelist wielding a powerful pulse cannon",
    AttackType: "Ranged",
    offense: 96,
    defense: 9,
    teamUtility: 32,
    mobility: 32,
    difficulty: "Easy",
  },
  {
    id: 27,
    img: "/hero/koshka.png",
    name: "Koshka",
    role: "Assassin",
    description:
      "Hit and run assassin who can pin down enemies with a long stun",
    AttackType: "Melee",
    offense: 100,
    defense: 26,
    teamUtility: 26,
    mobility: 88,
    difficulty: "Easy",
  },
  {
    id: 28,
    img: "/hero/krul.png",
    name: "Krul",
    role: "Warrior",
    description: "The king of duels with massive lifesteal and self healing",
    AttackType: "Melee",
    offense: 74,
    defense: 50,
    teamUtility: 10,
    mobility: 45,
    difficulty: "Medium",
  },
  {
    id: 29,
    img: "/hero/lance.png",
    name: "Lance",
    role: "Protector",
    description: "Disruptive knight who stops enemies in theri tracks",
    AttackType: "Melee",
    offense: 53,
    defense: 96,
    teamUtility: 90,
    mobility: 65,
    difficulty: "Hard",
  },
  {
    id: 30,
    img: "/hero/leo.png",
    name: "Leo",
    role: "Warrior",
    description: "Brawny bodyguard with a jet powered sword",
    AttackType: "Melee",
    offense: 90,
    defense: 31,
    teamUtility: 31,
    mobility: 75,
    difficulty: "Hard",
  },
  {
    id: 31,
    img: "/hero/lorelai.png",
    name: "Lorelai",
    role: "Protector",
    description:
      "Blackline support, excelling at zone control and team untility",
    AttackType: "Ranged",
    offense: 44,
    defense: 20,
    teamUtility: 98,
    mobility: 77,
    difficulty: "Medium",
  },
  {
    id: 32,
    img: "/hero/lyra.png",
    name: "Lyra",
    role: "Protector",
    description: "Healer and zone mage who can create teleportaion portals",
    AttackType: "Ranged",
    offense: 34,
    defense: 20,
    teamUtility: 100,
    mobility: 38,
    difficulty: "Hard",
  },
  {
    id: 33,
    img: "/hero/magnus.png",
    name: "Magnus",
    role: "Mage",
    description: "Powerful arcanist who decimates enemies from afar",
    AttackType: "Ranged",
    offense: 100,
    defense: 20,
    teamUtility: 50,
    mobility: 9,
    difficulty: "Medium",
  },
  {
    id: 34,
    img: "/hero/malene.png",
    name: "Malene",
    role: "Mage",
    description:
      "From swapping spellcaster who has the tools for any situation",
    AttackType: "Ranged",
    offense: 90,
    defense: 38,
    teamUtility: 90,
    mobility: 75,
    difficulty: "Hard",
  },
  {
    id: 35,
    img: "/hero/miho.png",
    name: "Miho",
    role: "Assassin",
    description: "Skilled swordswoman that can cut through any obstacle",
    AttackType: "Melee",
    offense: 97,
    defense: 48,
    teamUtility: 10,
    mobility: 100,
    difficulty: "Hard",
  },
  {
    id: 36,
    img: "/hero/ozo.png",
    name: "Ozo",
    role: "Assassin",
    description: "Acrobatic monkey with immense self healing",
    AttackType: "Melee",
    offense: 58,
    defense: 63,
    teamUtility: 33,
    mobility: 58,
    difficulty: "Hard",
  },
  {
    id: 37,
    img: "/hero/petal.png",
    name: "Petal",
    role: "Sniper",
    description:
      "Commands 3 pets who tear apart enemies and block incoming skillshots",
    AttackType: "Ranged",
    offense: 86,
    defense: 19,
    teamUtility: 50,
    mobility: 48,
    difficulty: "Easy",
  },
  {
    id: 38,
    img: "/hero/phinn.png",
    name: "Pninn",
    role: "Protector",
    description:
      "Extremely tanky and can pull in enemies from across the screen",
    AttackType: "Melee",
    offense: 146,
    defense: 100,
    teamUtility: 97,
    mobility: 1,
    difficulty: "Medium",
  },
  {
    id: 39,
    img: "/hero/reim.png",
    name: "Reim",
    role: "Mage",
    description: "Resilient ice mage who doimates close quarter battles",
    AttackType: "Melee",
    offense: 90,
    defense: 90,
    teamUtility: 70,
    mobility: 1,
    difficulty: "Meidum",
  },
  {
    id: 40,
    img: "/hero/reza.png",
    name: "Reza",
    role: "Assassin",
    description: "A fast, devastating fire mage wiht a demon netherform",
    AttackType: "Melee",
    offense: 90,
    defense: 40,
    teamUtility: 37,
    mobility: 75,
    difficulty: "Hard",
  },
  {
    id: 41,
    img: "/hero/ringo.png",
    name: "Ringo",
    role: "Sniper",
    description: "Fast moving, fast shooting gunslinger with an epic fireball",
    AttackType: "Ranged",
    offense: 80,
    defense: 20,
    teamUtility: 10,
    mobility: 47,
    difficulty: "Easy",
  },
  {
    id: 42,
    img: "/hero/rona.png",
    name: "Rona",
    role: "Melee",
    description: "Durable berserker who excels in thick of fights",
    AttackType: "Melee",
    offense: 84,
    defense: 79,
    teamUtility: 20,
    mobility: 79,
    difficulty: "Medium",
  },
  {
    id: 43,
    img: "/hero/saw.png",
    name: "SAW",
    role: "Sniper",
    description:
      "Heavy machine gunner who sacrifices movement speed for damage",
    AttackType: "Ranged",
    offense: 100,
    defense: 15,
    teamUtility: 15,
    mobility: 15,
    difficulty: "Easy",
  },
  {
    id: 44,
    img: "/hero/samuel.png",
    name: "Samuel",
    role: "Mage",
    description: "Dark zone contrl mage who can put enemies to sleep",
    AttackType: "Ranged",
    offense: 90,
    defense: 20,
    teamUtility: 20,
    mobility: 45,
    difficulty: "Hard",
  },
  {
    id: 45,
    img: "/hero/san-feng.png",
    name: "San Feng",
    role: "Warrior",
    description: "A master granger who turns his foe's power against them",
    AttackType: "Melee",
    offense: 68,
    defense: 93,
    teamUtility: 47,
    mobility: 41,
    difficulty: "Medium",
  },
  {
    id: 46,
    img: "/hero/shin.png",
    name: "Shin",
    role: "Warrior",
    description: "Divine warrior with cybernetic augmentaions",
    AttackType: "Melee",
    offense: 92,
    defense: 70,
    teamUtility: 69,
    mobility: 92,
    difficulty: "Medium",
  },
  {
    id: 47,
    img: "/hero/silvernail.png",
    name: "Silvernail",
    role: "Sniper",
    description: "Grizzled hunter with a powerful crossbow and tripwires",
    AttackType: "Ranged",
    offense: 84,
    defense: 20,
    teamUtility: 89,
    mobility: 8,
    difficulty: "Hard",
  },
  {
    id: 48,
    img: "/hero/skaarf.png",
    name: "Skaarf",
    role: "Mage",
    description: "Spits long range fireballs and incinerates entire teams",
    AttackType: "Ranged",
    offense: 94,
    defense: 22,
    teamUtility: 28,
    mobility: 10,
    difficulty: "Easy",
  },
  {
    id: 49,
    img: "/hero/skye.png",
    name: "Skye",
    role: "Sniper",
    description:
      "Versatile elusive mech pilot who can flank enemies from any angel",
    AttackType: "Ramged",
    offense: 97,
    defense: 17,
    teamUtility: 29,
    mobility: 95,
    difficulty: "Hard",
  },
  {
    id: 50,
    img: "/hero/taka.png",
    name: "Taka",
    role: "Assassin",
    description: "Stealthy assassin who can heal while invisible",
    AttackType: "Melee",
    offense: 48,
    defense: 49,
    teamUtility: 10,
    mobility: 88,
    difficulty: "Medium",
  },
  {
    id: 51,
    img: "/hero/tony.png",
    name: "Tony",
    role: "Warrior",
    description: "Dwarven brawler who taunts and pummels enemies",
    AttackType: "Melee",
    offense: 89,
    defense: 75,
    teamUtility: 60,
    mobility: 55,
    difficulty: "Medium",
  },
  {
    id: 52,
    img: "/hero/varya.png",
    name: "Varya",
    role: "Mage",
    description:
      "Shocking valkyie who chains massive damage across enemy teams",
    AttackType: "Ranged",
    offense: 97,
    defense: 32,
    teamUtility: 25,
    mobility: 78,
    difficulty: "Hard",
  },
  {
    id: 53,
    img: "/hero/viola.png",
    name: "Viola",
    role: "Protector",
    description: "A wandering musician with a mysterious magical instrument",
    AttackType: "Ranged",
    offense: 96,
    defense: 37,
    teamUtility: 23,
    mobility: 100,
    difficulty: "Hard",
  },
  {
    id: 54,
    img: "/hero/vox.png",
    name: "Vox",
    role: "Sniper",
    description: "Agile damage dealer who dashes around the battlefield",
    AttackType: "Ranged",
    offense: 85,
    defense: 22,
    teamUtility: 22,
    mobility: 98,
    difficulty: "Medium",
  },
  {
    id: 55,
    img: "/hero/warhawk.png",
    name: "Warhawk",
    role: "Mage",
    description: "Smallest hero wielding the biggest missile launcher",
    AttackType: "Ranged",
    offense: 94,
    defense: 8,
    teamUtility: 50,
    mobility: 77,
    difficulty: "Easy",
  },
  {
    id: 56,
    img: "/hero/yates.png",
    name: "Yates",
    role: "Proctector",
    description: "Armored commander who pulls in foes and has global presence",
    AttackType: "Melee",
    offense: 10,
    defense: 20,
    teamUtility: 96,
    mobility: 64,
    difficulty: "Medium",
  },
  {
    id: 57,
    img: "/hero/ylva.png",
    name: "Ylva",
    role: "Assassin",
    description: "Huntress that stalks her prey and lays traps for them",
    AttackType: "Ranged",
    offense: 79,
    defense: 23,
    teamUtility: 80,
    mobility: 9,
    difficulty: "Hard",
  },
];
