// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import Navbar from "./Component/navbar/Navbar";
// import Footer from "./Component/footer/footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// ////jhfdhbfhdsbfjsdf

// export const metadata: Metadata = {
//   title: "Vainglory",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />

//         {children}

//         <Footer />
//       </body>
//     </html>
//   );
// }
<<<<<<< HEAD
<div className="hero-card bg-blue-500 text-white">
  <Image
    src={heroImg}
    alt={heroName}
    width={150}
    height={200}
    onClick={() => setOpenModal(true)}
  />

  <h2 className="text-center font-bold mt-2">
    {heroName}
  </h2>
</div>
=======
<div className="hero-card bg-red-500 text-black">
  <Image
    src={heroImg}
    alt="hero image"
    width={170}
    height={220}
    onClick={() => setOpenModal(true)}
  />

  <h2 className="text-center italic mt-2">
    {heroName} - {heroRole}
  </h2>
</div>
>>>>>>> feature/new-hero-ui